name: Deploy to AWS ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Verify environment variable
      run: |
        echo "VITE_API_URL will be set to: ${{ vars.VITE_API_URL }}"
        if [ -z "${{ vars.VITE_API_URL }}" ]; then
          echo "ERROR: VITE_API_URL is not set in GitHub variables"
          exit 1
        fi

    - name: Build, tag, and push image to Amazon ECR
      id: build
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo "Building with VITE_API_URL=${{ vars.VITE_API_URL }}"
        echo "Build args: VITE_API_URL=\"${{ vars.VITE_API_URL }}\""
        
        docker buildx build \
          --platform linux/amd64 \
          --build-arg VITE_API_URL="${{ vars.VITE_API_URL }}" \
          --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
          --tag $ECR_REGISTRY/$ECR_REPOSITORY:latest \
          --push \
          .

        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Output image URI
      run: echo "Image pushed to ${{ steps.build.outputs.image }}" 